package cn.pear.bean;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.id
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_name
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_gender
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    private Integer teacherGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.address
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.course
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    private String course;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.id
     *
     * @return the value of t_teacher.id
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.id
     *
     * @param id the value for t_teacher.id
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_name
     *
     * @return the value of t_teacher.teacher_name
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_name
     *
     * @param teacherName the value for t_teacher.teacher_name
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_gender
     *
     * @return the value of t_teacher.teacher_gender
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public Integer getTeacherGender() {
        return teacherGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_gender
     *
     * @param teacherGender the value for t_teacher.teacher_gender
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public void setTeacherGender(Integer teacherGender) {
        this.teacherGender = teacherGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.address
     *
     * @return the value of t_teacher.address
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.address
     *
     * @param address the value for t_teacher.address
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.course
     *
     * @return the value of t_teacher.course
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.course
     *
     * @param course the value for t_teacher.course
     *
     * @mbg.generated Wed Nov 04 17:48:51 CST 2020
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }
}